### ISSUE TITLE
Add Hover Effect on NavLinks

### ISSUE THREAD

**Issue by programmer-rahul** [programmer-rahul/personal-portfolio#2]
Add hover effects on navigation links in header.

**Comment by doriroz** [comment]
if this issue still open, i can take it

**Comment by programmer-rahul** [comment]
Thank you for your interest, @doriroz. Currently, @yashksaini-coder is working on this issue, and I'm waiting for him to make the suggested changes. If he doesn't respond or make the changes, you can take over. In the meantime, feel free to suggest any good hover effects for the nav links that we could consider for future use. Thank you for your willingness to contribute!

**Comment by yashksaini-coder** [comment]
@programmer-rahul I have made some new changes and you can check them out #3 
I hope you like the changes and meet your requirements.

**Comment by programmer-rahul** [comment]
The hover effect on the Nav links has been successfully implemented and merged in PR #3 . Thanks to everyone for their contributions! Closing this issue now.
