### ISSUE TITLE
Add Hover Effect for Buttons

### ISSUE THREAD

**Issue by programmer-rahul** [programmer-rahul/personal-portfolio#4]
Add a hover effect for the buttons on the website. The hover effect should be visually appealing. Additionally, please remove the secondary button since it is not used frequently. Focus on creating a well-designed primary button with a good hover effect.

**Comment by Yashop181** [comment]
I am planning to enhance the button design on our website. Specifically, I will add a visually appealing hover effect for the primary buttons and remove the secondary button since it is not frequently used. To proceed, could you please confirm if you are referring to the design shown in the attached screenshot?
![Screenshot (1167)](https://github.com/user-attachments/assets/17631d54-b80c-47f8-812c-e5e0b1b2da46)


Looking forward to your confirmation.

**Comment by programmer-rahul** [comment]
Yes

**Comment by Yashop181** [comment]
Sure, I will make the changes.

**Comment by Yashop181** [comment]
Hi @programmer-rahul,

![Screenshot (1194)](https://github.com/user-attachments/assets/d3133a40-5f90-44a0-8cdd-170476cecc1d)
![Screenshot (1195)](https://github.com/user-attachments/assets/7512e3e3-6097-4365-8056-6bd5acf6e331)

**Comment by Yashop181** [comment]
Hi @programmer-rahul ,

I’ve shared two screenshots showing the updated button design with the new hover effects.
Screenshot 1: 
![Screenshot (1194)](https://github.com/user-attachments/assets/0b0ee29e-aafc-4aca-8ee0-ec1a81165bda)


Screenshot 2: 
![Screenshot (1195)](https://github.com/user-attachments/assets/dab6c876-687e-4049-b46d-df4090242f9c)

Please review these changes and let me know if they meet your expectations or if any further adjustments are needed.

Looking forward to your feedback!

**Comment by programmer-rahul** [comment]
@Yashop181 , Actually, both are good, but you should consider using the website's main color, like the purple used elsewhere. Introducing a new color for the button, such as pink, should not be a good option since it hasn't been used anywhere on the website. However, it's better to use a color that matches our website theme. What do you think?

**Comment by Yashop181** [comment]
Hi @programmer-rahul ,

I'll update the button colors to match our website's purple theme for consistency.

**Comment by Yashop181** [comment]
Hi @programmer-rahul ,

I've updated the button colors to match our website's purple theme. The first image shows the button in its normal state, and the second image shows the hover effect.

What are your thoughts on this change?

Normal State:

![Screenshot (1196)](https://github.com/user-attachments/assets/6f278ddc-a5f2-4b31-b20c-9d6c21481234)

Hover Effect:

![Screenshot (1197)](https://github.com/user-attachments/assets/c96a57a8-05b6-4f25-b6c4-28335026c995)

**Comment by programmer-rahul** [comment]
Hi @Yashop181,

Thank you for updating the button colors to match our website's purple theme. It looks good! However, the hover state is quite simple, with just an opacity or color change. It would be great if you could use a more modern hover effect. You can check out this link for inspiration: [CSS Buttons Examples](https://getcssscan.com/css-buttons-examples). Please choose one that fits best with our website.

**Comment by Yashop181** [comment]
Hi @programmer-rahul,

I have updated the button hover effect to match our website's purple theme, as per the inspiration from the CSS Buttons Examples. The new hover effect has been implemented and you can see the changes in the attached video.

https://github.com/user-attachments/assets/ba47080c-bdf1-41c0-81a2-8789f2664548

Please review the changes and let me know your thoughts.

**Comment by programmer-rahul** [comment]
The new hover effect looks good based on the video. Please go ahead and create a pull request so we can review it in real-time on the website.

**Comment by Yashop181** [comment]
Sure, I will create the PR.

**Comment by Yashop181** [comment]
Hi @programmer-rahul ,

I have created a PR for the new hover effect. Please review it.

**Comment by programmer-rahul** [comment]
closes by pr#6

**Comment by programmer-rahul** [comment]
closed by pr#6
